version: 2
jobs:
  build:
    docker:
      - image: jloh/geojs-tests:beta-0.0.5
    steps:
      - checkout
      # We have to do it this way since wget'ing it lands us weird dir names
      - run:
          name: 'Download GoeLite2 Maxmind DBs'
          command: |
            mkdir -p download-cache/maxmind2
            cp .circleci/Geoip.conf /etc/GeoIP.conf
            geoipupdate -v
      - run:
          name: 'Install OPM dependencies'
          command: |
            opm install \
            pintsized/lua-resty-http=0.12 \
            openresty/lua-resty-dns=0.21 \
            openresty/lua-resty-upload=0.10 \
            bungle/lua-resty-reqargs=1.4 \
            xiaooloong/lua-resty-iconv=0.2.0 \
            anjia0532/lua-resty-maxminddb=0.06
      - run:
          name: 'Add in Maxmind ASN'
          command: |
            mkdir -p lib/resty
            curl -s -o lib/resty/maxminddb_asn.lua $MAXMIND_LUA_URL
      - run:
          name: 'Nginx version'
          command: nginx -V
      - run:
          name: 'Tests'
          command: prove -r t -a test_results.tgz
      - run:
          name: 'Test Coverage'
          command: |
            if [[ "${TEST_COVERAGE}x" == '1x' ]]; then luacov; fi
            if [[ "${TEST_COVERAGE}x" == '1x' ]]; then luacov-coveralls; fi
      - store_artifacts:
          path: test_results.tgz

notify:
  webhooks:
    # A list of hook hashes, containing the url field
    # gitter hook
    - url: https://webhooks.gitter.im/e/52d0ede6149c8fcdf4cd
